### ISSUE TITLE
Getting error : The new decorators proposal is not supported yet. You must pass the `"decoratorsLegacy": true` option to @babel/preset-stage-2 

### ISSUE THREAD

**Issue by jaydeep82** [start-react/sb-admin-seed-react#5]
Any help would be great here.
npm : v6.0.0
node : v8.11.1

https://github.com/start-react/sb-admin-seed-react/blob/master/docs/getting-started.md

Getting following error in Step 3 :  Run **npm start**

```
sudo npm start

> web@0.0.0 start /Volumes/S/test/MyApp
> babel-node tools/run start

/Volumes/S/test/MyApp/node_modules/@babel/core/lib/config/full.js:139
    throw e;
    ^

Error: [BABEL] /Volumes/S/test/MyApp/tools/run.js: The new decorators proposal is not supported yet. You must pass the `"decoratorsLegacy": true` option to @babel/preset-stage-2 (While processing: "/Volumes/S/test/MyApp/node_modules/@babel/preset-stage-2/lib/index.js")
    at /Volumes/S/test/MyApp/node_modules/@babel/preset-stage-2/lib/index.js:107:11
    at /Volumes/S/test/MyApp/node_modules/@babel/helper-plugin-utils/lib/index.js:18:12
    at /Volumes/S/test/MyApp/node_modules/@babel/core/lib/config/full.js:172:14
    at cachedFunction (/Volumes/S/test/MyApp/node_modules/@babel/core/lib/config/caching.js:42:17)
    at loadPresetDescriptor (/Volumes/S/test/MyApp/node_modules/@babel/core/lib/config/full.js:243:63)
    at /Volumes/S/test/MyApp/node_modules/@babel/core/lib/config/full.js:68:19
    at Array.map (<anonymous>)
    at recurseDescriptors (/Volumes/S/test/MyApp/node_modules/@babel/core/lib/config/full.js:66:36)
    at loadFullConfig (/Volumes/S/test/MyApp/node_modules/@babel/core/lib/config/full.js:112:6)
    at loadOptions (/Volumes/S/test/MyApp/node_modules/@babel/core/lib/config/index.js:28:34)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web@0.0.0 start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jay/.npm/_logs/2018-04-27T10_59_04_547Z-debug.log

```

**Comment by jaydeep82** [comment]
https://github.com/babel/babel/issues/7786
